server:
  port: 8070
spring:
  profiles:
    active: '@profileActive@'
  application:
    name: '@pom.artifactId@'
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.229.199:3306/campus_organization?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: eR7uG5v6XEwjaqwd[]C9
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    database: 1
    host: 47.111.229.199
    port: 6379
    timeout: 10000
  rabbitmq:
    host: 112.126.88.157
    username: organ
    password: organ
    virtual-host: /organ
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: auto
    port: 15672
  servlet:
    multipart:
      max-file-size: -1MB
      max-request-size: -1MB

logging:
  level:
    root: INFO
    org.apache.ibatis: info
    java-utils: debug
  config: classpath:logback.xml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  returnPageInfo: check

upload-file:
  imgPath: /images/admin-organization
  imgUrl: http://vip.amsure.cn:8050/images/admin-organization/
  imgThumbPath: /images/admin-organization
  imgThumbUrl: http://vip.amsure.cn:8050/thumb/

token:
  secretKey: 9ac93552c203dde2a133a0988faa05b9
  ttl: 7

swagger:
  enable: true

url:
  white-list:
    - /doc.html
    - bycdao-ui
    - swagger-resources
    - /school/master/getIntroduction
    - /file/img/upload
    - /others/selectStudentList
    - /others/getTeacherRoles
    - /others/getStudentByIdNumber
    - /others/getStudentTeacherByIdNumber
    - /others/getIdNumberByUserId
    - /others/getFaceImgInfo
    - /others/getTeacherForMiniApp
    - /others/getTeacherByPhone
    - /others/getStudentAndTeacherInfo
    - /others/selectBuildingList
    - /others/getBuildingInfoListByIds
    - /others/getStudentsByRoom
    - /others/getStudentsOrTeachersByType
    - /others/getStudentByTeacherId
    - /others/getStudentCountByTeacherPhone
    - /others/getAllStudents
    - /others/getAllTeachers
    - /others/getAllBuildings
    - /others/getPersonsByType
    - /others/getBuildingNoAndLevels
    - /others/getStudentTeacherByStudentId
    - /others/getStudentInfoById
    - /others/getStudentsByTeacherId
    - /others/getTotalByGradeId
    - /others/classes
    - /others/info
    - /others/ttt
    - /others/masters
    - /admin/check
    - /admin/token
    - /admin/exit
